[package]
name = "prime-number-catacombs"
version = "0.1.0"
authors = ["Bryan McClain <bamcclain10@gmail.com>"]
description = "Rust WASM backend to run the Prime Number Catacombs"
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.74"
